### ISSUE TITLE
Code duplication?

### ISSUE THREAD

**Issue by AdaDoom3** [DustinHLand/vkDOOM3#10]
It would seem that Vulkan/BufferObject_VK.cpp features a stunning amount of code duplication.

Why not have a single buffer object type with an enum (e.g. t_bufferType for vertex, index, uniform, etc) or use inheritance to case out the buffercreateinfo usage and sharing flags. In the very least creating some internal library-like functions for common functionality would save a lot of LoC : )

**Comment by DustinHLand** [comment]
Not particularly a fan of it myself, but historically it was setup that way.  If you look at BFG's source it didn't even have idBufferObject and idUniformBuffer was idJointBuffer.  It's on my list to make it nicer, but it's lower on my priority.  If you want to make a pull request, I'd be happy to look at it. :)

**Comment by AdaDoom3** [comment]
Ok, i'll see what I can brew up ;)
