### ISSUE TITLE
GPU clocks fluctuation

### ISSUE THREAD

**Issue by antonl1911** [DustinHLand/vkDOOM3#11]
I am running vkDOOM3 on Windows 10 x64, with RX 560 4G GPU (17.8.1 driver) and the issue is that FPS is between 40 and 60, and I can see in RTSS overlay that GPU clock is constantly fluctuating below 1000 Mhz, like there is not enough load put on a GPU to justify full clock power state. It's observed with either binary release or self-built version.

**Comment by DustinHLand** [comment]
You can try  +set r_swapInterval 0 +set com_engineHz <higher than 60>.  That may have adverse effects on other game systems, but if you're trying to put more load on the GPU, that'll do it.  You can also turn on MSAA +set r_multiSamples [ 2, 4, 8, 16 ].  BFG isn't really going to push modern hardware very much even if it's optimized more.  Assets would need to be updated.  The lack of driver overhead in Vulkan already makes it 4x faster than GL on the API portion.  I don't have an AMD card I can play with atm, just Nvidia.

**Comment by DustinHLand** [comment]
Also what version are you using? ( what commit as well )

**Comment by antonl1911** [comment]
I was using master then and using master now, but after 7b5a1424cd84cff6acb41277ac1b1fce5c0f00c2 some rendering problems appeared: something is wrong with "camera".

**Comment by DustinHLand** [comment]
I did fix a bug recently.  Try latest.

**Comment by antonl1911** [comment]
Latest sources has fixed the camera problem. And the clocks problem is indeed caused by refresh rate limiting.

**Comment by DustinHLand** [comment]
Awesome glad that fixed it :)
