### ISSUE TITLE
Port for RBDoom 3 BFG?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [DustinHLand/vkDOOM3#12]
Hello.

Is there any way to get this to work for RBDoom 3 BFG? Here is a link to the project in case you don't know what I am talking about: https://github.com/RobertBeckebans/RBDOOM-3-BFG

Basically, it's Doom 3 BFG, but with added soft shadows, 64-bit builds and countless bug fixes. I have not been able to get this Vulkan port to work with it.

If it is not too much trouble, I would like to request a port of this for RBDoom 3 BFG please.

**Comment by RobertBeckebans** [comment]
It is already on my TODO list. See https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/398

**Comment by ROCKNROLLKID** [comment]
Good to know. Thanks.
