### ISSUE TITLE
360 deg. stereo screenshot

### ISSUE THREAD

**Issue by motorsep** [DustinHLand/vkDOOM3#15]
Is there any way you could add new screenshot functionality where 360 deg. panoramic stereo screenshot is taken (top/bottom for equirecs and left to right strip for cubemap) ? In this age of VR flat 2D screenshots seem to be obsolete ;)

Thanks beforehand!

**Comment by DustinHLand** [comment]
That's not really something on my radar to add.  I do know someone that's interested in doing VR stuff with the code base though.  I can leave this open for them to see.

**Comment by motorsep** [comment]
Fair enough, although generating 360 deg. stereo screenshots has very little to do with VR implementation :)

**Comment by sullit** [comment]
from the Ansel docs, the SDK only support's DXapi backbuffer formats for the linker

<quote>1.3 GAME ENGINE CONFIGURATION

Ansel currently supports the following backbuffer formats:

DXGI_FORMAT_R8G8B8A8_UNORM
DXGI_FORMAT_R8G8B8A8_UNORM_SRGB
DXGI_FORMAT_B8G8R8A8_UNORM
DXGI_FORMAT_B8G8R8A8_UNORM_SRGB
DXGI_FORMAT_R10G10B10A2_UNORM</quote>

so it's unlikely that without vk buffer binding's that 360 stereo shot's will be possible

**Comment by DustinHLand** [comment]
I don't know enough about the technology to weigh in on this.  It's not something I've ever done or familiarized myself with.  If someone wants to add support, they're welcome to.

**Comment by BielBdeLuna** [comment]
do an env shot and then you unwrap it as a 360 shot

**Comment by motorsep** [comment]
@BielBdeLuna It doesn't work like like that for stereo

**Comment by BielBdeLuna** [comment]
do and envshot for every camera

**Comment by motorsep** [comment]
@BielBdeLuna Why bring poor arguments to the table when you haven't tried it yourself?! It doesn't work!

**Comment by BielBdeLuna** [comment]
why is it a poor argument then?
