### ISSUE TITLE
Update Vulkan SDK to 1.0.61?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [DustinHLand/vkDOOM3#16]
A few days ago, Vulkan SDK 1.0.61 was released that contain a number of bug fixes and some new extensions. Perhaps worth updating to?

**Comment by DustinHLand** [comment]
I'll take a look. Thx :)

**Comment by ROCKNROLLKID** [comment]
There was a 1.0.61.1 updated that included a few bug fixes, would recommend using that over 1.0.61.

**Comment by ROCKNROLLKID** [comment]
Just letting you know 1.0.65 was released 2 days ago. Might as well grab the latest version.

**Comment by DustinHLand** [comment]
Sorry for late response on this.  The sln now uses the VULKAN_SDK env variable.  Cheers
