### ISSUE TITLE
Question about BlockingSwapBuffers()

### ISSUE THREAD

**Issue by Mercesa** [DustinHLand/vkDOOM3#18]
Hello, so I am using the VulkanBackend as a reference on how to properly set up my own Vulkan renderer but something has started to irk me when looking a bit into it.

As far as my understanding goes, lockless frame rendering should go as follows.

1. Prepare work
2. Wait for the GPU to be done
3. Submit Work
4. Present
5. While work is being processed by GPU, start at 1 again 

But I realized that in `BlockingSwapBuffers()` there is a fence operation as such.

`context.device.waitForFences(context.commandBufferFences[context.currentFrame], VK_TRUE, UINT64_MAX);
context.device.resetFences(context.commandBufferFences[context.currentFrame]);`

If the pipeline is GL_BeginFrame() -> GL_EndFrame() -> BlockingSwapBuffers()

Then the work is prepared from GL_BeginFrame to GL_Endframe, submitted within GL_EndFrame and then waited on during BlockingSwapBuffers().

But is this not the antithesis of how lockless rendering works? Since now it seems to me that the GPU processes, CPU waits on GPU to be done, then presents the image. So there is no work done during the time the GPU is processing due to the fences in blocking swap buffers.

What is described in the below link is something that does not seem to happen in the Vulkan Backend, which makes me question why there is a variable to have several frames at all, since everything seems locked.

https://stackoverflow.com/questions/35563795/vulkan-samples-vkqueuesubmit-always-followed-by-vkwaitforfences

**Comment by DustinHLand** [comment]
It depends if com_smp is one or zero.  Zero will block sooner, but one will not till the top of the next frame.  Look for com_smp in common_frame.cpp.  Zero is mainly used for debugging.  One is used for runtime.

**Comment by DustinHLand** [comment]
Sorry for late response btw.  Been busy with other things.

**Comment by DustinHLand** [comment]
Actually I see the problem now.  Going to refactor a bit.  The API from Common::Frame -> Renderer isn't the nicest for this.

**Comment by Mercesa** [comment]
I am sorry myself, I have forgotten to answer to your previous reply :). Let me know when you've refactored it though since I am curious about what you have done.

**Comment by DustinHLand** [comment]
I moved the present to happen after the queue submission ( using the sync primitives ).  I also just increment the frame early and wait for it.  Being double buffered, it's rather simple.  Frontend should wait on the oldest cmdbuf submitted, which it does now.

**Comment by DustinHLand** [comment]
Gonna close this out now, but thanks for bringing my attention to it.  Cheers.
