### ISSUE TITLE
vkWaitForFences breaks GPU/CPU pipelining

### ISSUE THREAD

**Issue by cforfang** [DustinHLand/vkDOOM3#2]
Hi Dustin,

It looks like there are two places in the current code where ``vkWaitForFences`` is called on command-buffers submitted in the same frame.

1. In ``idVulkanStagingManager::Wait()`` (called from ``idVulkanStagingManager::Flush()``) where it waits on ``stage.commandBuffer`` which was just submitted. 
2. In ``idRenderBackend::BlockingSwapBuffers`` where it waits on ``vkcontext.commandBufferFences[ vkcontext.currentFrameData ]`` which seems to have been submitted in ``idRenderBackend::GL_EndFrame``. (``vkcontext.currentFrameData`` is then rotated afterwards).

This seem not ideal because it forces CPU/GPU synchronisation unnecessarily.

For 1) it seems like you can either use pipeline-barrier(s) to make sure the operations in ``stage.commandBuffer`` have completed and are made available to the command-buffer(s) that are submitted after it (either one global memory barrier added to the end, or make it up to the callers of``idVulkanStagingManager::Stage()`` to add the appropriate barriers to the returned command-buffer). Or alternatively,  since ``idVulkanStagingManager::Flush()`` calls ``vkQueueSubmit``, a semaphore between the staging-submit and the submit in ``idRenderBackend::GL_EndFrame``.

(I think you technically need one of these anyway so results of the operations inside the staging-command buffer (e.g. the``vkCmdCopyBuffer``s ) are made visible to later GPU ops -- i.e. just waiting for execution to finish using the fence isn't enough, you need barrier(s) or semaphores to make sure the correct cache flushes happen.)

For 2) I'm not sure why the wait is there? Should it wait on the next ``vkcontext.currentFrameData`` fence instead, so that data of in-flight frames aren't overwritten, or is there a reason to block the CPU while waiting on the current frame to finish (i.e. no pipelining)? 

Cheers,
Christian

**Comment by DustinHLand** [comment]
Hey Christian,

Thanks for a thorough write up.  I'll take a closer look at it tonight and get back with you.

Cheers

**Comment by DustinHLand** [comment]
Check out 84607dd.  I refactored Flush so it uses a memory barrier from transfer -> input and doesn't wait on the fence.  Instead the the mgr waits on the fence when it round robins back to a previously submitted buffer.  At this point that one should have completed meaning the wait just returns.  Note that the staging manager isn't used while in level.  All the loading happens in map transition ( unless there's something I don't know of ).

**Comment by cforfang** [comment]
Sorry for the late reply. Fix looks good :)

Any thoughts on the second wait in ``idRenderBackend::BlockingSwapBuffers``? Doesn't having it sort of defeat the purpose of having ``vkcontext.currentFrameData`` in the first place since there are never multiple frames in flight?
