### ISSUE TITLE
Incorrect GLS_CULL_BITS' value in GLState.h 

### ISSUE THREAD

**Issue by jammymalina** [DustinHLand/vkDOOM3#20]
Hi ladies and gents, I noticed an incorrect value for GLS_CULL_BITS in GLState.h: static const uint64 GLS_CULL_BITS = 2 << 15 should be 7 << 15; Potentially, we can save 1 bit if we changed it to 3 << 15 but that would require changing all the values after GLS_CULL_BITS.

**Comment by DustinHLand** [comment]
I see the problem, thanks for pointing it out.  However CULL only needs two bits so 7 << 15 will push into BLENDOP.  3 << 15 == GLS_CULL_MASK which is what GLS_CULL_BITS should function as.  

10000000000000000 = GLS_CULL_BITS
11000000000000000 = GLS_CULL_MASK
11000000000000000 = 3 << 15
111000000000000000 = 7 << 15

Fix incoming.

**Comment by DustinHLand** [comment]
Fixed in abe98fd.  Thanks for the report :)
