### ISSUE TITLE
Non-english locales only display string placeholders

### ISSUE THREAD

**Issue by SaschaWillems** [DustinHLand/vkDOOM3#3]
I'm running on a german copy of the game (which has no english or other language files) and noticed that I have only the string placeholders visible in Doom3 BFG:

![d3bfggerman](https://user-images.githubusercontent.com/10283127/29231445-7a8b780a-7ee7-11e7-908c-15067a408a06.png)

I did some debugging trying to get it to use german language as default:

![image](https://user-images.githubusercontent.com/10283127/29231489-ac20bf6a-7ee7-11e7-9b6a-134173316727.png)

But even with that change the ```idCommonLocal::FilterLangList``` function still gets "english" passed as the language to filter out, which seems to be caused by a difference in the cvar value and it's internal value:

![image](https://user-images.githubusercontent.com/10283127/29231559-fa2f20fc-7ee7-11e7-8dc1-8f1c5c12dd33.png)

Passing ```+seta sys_lang "german"``` doesn't work either.

Since I don't have any other language files I don't want to change that code yet, but I guess you have access to all the language files anyway ;)

**Comment by DustinHLand** [comment]
Yep I'll take a look. Thanks for report. ( issue closed/reopened due to fat finger )

**Comment by DustinHLand** [comment]
I have to imagine this is due to Sys_SetLanguageFromSystem being called in idCommonLocal::Init.  It calls Sys_DefaultLanguage which obviously has sku code removed.  So probably got moved in platform culling for GPL release.

**Comment by DustinHLand** [comment]
Commit e6667b4 will let you override by setting sys_lang.

**Comment by SaschaWillems** [comment]
I can confirm that this is working now. Thx!
