### ISSUE TITLE
Windows Binaries (32 - 64)

### ISSUE THREAD

**Issue by donizettilorenzo** [DustinHLand/vkDOOM3#4]
Can you provide (for lazy people :D ) a ready-to-use 32 bit build and a 64 bit build of vkDoom3 (in the "releases" section)?
Thanks!

**Comment by DustinHLand** [comment]
Hi, I added a 32 bit binary. I don't have 64 bit atm as BFG didn't support it.  But I intend on adding it later.  Enjoy!
