### ISSUE TITLE
SPIRV shader GUI problem

### ISSUE THREAD

**Issue by donizettilorenzo** [DustinHLand/vkDOOM3#5]
With the released binaries:

https://s9.postimg.org/was01iz9r/Untitled.jpg

**Comment by donizettilorenzo** [comment]
Solved, I used renderprogs from the source package ;)

**Comment by DustinHLand** [comment]
Ah I'll rezip and include them + instructions. Thx :)

**Comment by DustinHLand** [comment]
New Release v0.91.0 includes the spriv/glsl shaders.  Enjoy!
