### ISSUE TITLE
Glass shader extreme deformation

### ISSUE THREAD

**Issue by donizettilorenzo** [DustinHLand/vkDOOM3#6]
Is this intended? Just take a step very near a glass surface in Mars City:

https://postimg.org/image/6v1l3kix3/

**Comment by DustinHLand** [comment]
Yeah this is on my hit list to address. Thx for report.

**Comment by BielBdeLuna** [comment]
no, this is too much deformation

in RBDoom3BFG: https://postimg.org/image/ni31mi80d/

**Comment by DustinHLand** [comment]
Yeah it's definitely a known issue.  Check my TODO list on README.

**Comment by DustinHLand** [comment]
Fixed in 09895e3.  Single character change in heathaze vertex shader to account for Vulkan's different coord system.
