### ISSUE TITLE
[0.91] Texture alpha channel issue

### ISSUE THREAD

**Issue by donizettilorenzo** [DustinHLand/vkDOOM3#8]
Take a look:

http://postimg.org/image/prylulc6z/
http://postimg.org/image/sakav9xx7/

**Comment by RobertBeckebans** [comment]
I can confirm this with my Sapphire RX 580 card.

**Comment by DustinHLand** [comment]
Thanks for the reports 👍 I'll look into it.

**Comment by DustinHLand** [comment]
Fixed at head.
